
export default {
    path:"/seefilm",
    component:()=>import("views/seefilm"),
    name:"seefilm",
    redirect:"seefilm/recommend",
    meta:{
        tabBer:true,
        auth:true
   },
    children:[
        {
            path:"recommend",
            component:()=>import("components/recommend"),
            name:"recommend",
            meta:{
                tabBer:true,
                auth:true
           },
         },
         {
            path:"free_movies",
            component:()=>import("components/free_movies"),
            name:"free_movies",
            meta:{
                tabBer:true,
                auth:true
           },
        },
        {
            path:"show_list",
            component:()=>import("components/show_list"),
            name:"show_list",
            meta:{
                tabBer:true,
                auth:true
           },
        },
        {
            path:"small_video",
            component:()=>import("components/small_video"),
            name:"small_video",
            meta:{
                tabBer:true,
                auth:true
           },
        },
        {
            path:"film_review",
            component:()=>import("components/film_review"),
            name:"film_review",
            meta:{
                tabBer:true,
                auth:true
           },
        },

    ]
}