export default {
    path:"/buyticket",
    component:()=>import("views/buyticket"),
    name:"buyticket",
    redirect:"buyticket/film",
    meta:{
         tabBer:true,
         auth:true
    },
    children:[
        {
            path:"cinema",
            component:()=>import("components/cinema"),
            name:"cinema",
            meta:{
                tabBer:true,
                auth:true
           },
        },
        {
            path:"film",
            component:()=>import("components/film"),
            name:"film",
            redirect:"film/movienow",
            meta:{
                tabBer:true,
                auth:true
           },
            children:[
                    {
                        path:"movienow",
                        component:()=>import("components/movienow"),
                        name:"movienow",
                        meta:{
                            tabBer:true,
                            auth:true
                       },
                    },
                    {
                        path:"moviecoming",
                        component:()=>import("components/moviecoming"),
                        name:"moviecoming",
                        meta:{
                            tabBer:true,
                            auth:true
                       },
                    }
                ]
        },
        
    ]
}